POST  http://localhost:9090/user/
Accept: application/json
Content-Type: application/json

{
  "firstName": "Stanley",
  "middleName": "Martin",
  "lastName": "Lieber",
  "username": "Stan Lee",
  "mobile": "+7 800 5000 200",
  "email": "stanleyml@inbox.com",
  "intro": "Everything has beauty, but not everyone sees it.",
  "profileInfo": "An American comic book writer, editor, publisher, and producer"
}

###
PUT http://localhost:9090/user/104
Accept: application/json
Content-Type: application/json

{
  "middleName": "Parker",
  "lastName": "Robertson",
  "username": "Uncle Ben",
  "mobile": "+7 800 5000 500",
  "email": "cliffordpr@gmail.com",

  "profileInfo": "American actor"
}

###
GET http://localhost:9090/user/104
Accept: application/json

###
GET http://localhost:9090/user/all
Accept: application/json