server:
  port: 9061

spring:

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: messagingdb
      uri: mongodb://127.0.0.1:27017/messagingdb
      username: rootUser
      password: rootPassword
      authentication-database: admin

    redis:
      host: 127.0.0.1
      port: 6379

      jedis:
        pool:
          max-active: 50
          max-idle: 50
          min-idle: 0
          time-between-eviction-runs: 3s
          max-wait: 2s


  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: 890
    topic:
      name:

debug: true

