###
GET http://localhost:9090/posts/104
Accept: application/json

###
PUT http://localhost:9090/posts/104
Accept: application/json
Content-Type: application/json

{
  "senderId": 1470,
  "message": "Denn immer wenn ich einsam bin, zieht es mich zum Dunkel hin"
}