server.port: 9090

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: 'password'
    url: jdbc:h2:staging
    username: SA

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    password: 'password'
    url: jdbc:h2:staging
    username: SA