#!/bin/sh
kafka-topics.sh --create --bootstrap-server kafka-2:9096 --replication-factor 1 --partitions 1 --topic test_topic_1_kafka_2
kafka-topics.sh --create --bootstrap-server kafka-2:9096 --replication-factor 1 --partitions 1 --topic test_topic_2_kafka_2