### create user
POST  http://localhost:9090/users
Accept: application/json
Content-Type: application/json

{
  "firstName": "Stanley",
  "middleName": "Martin",
  "lastName": "Lieber",
  "username": "Stan Lee",
  "mobile": "+7 800 5000 200",
  "email": "stanleyml@inbox.com",
  "intro": "Everything has beauty, but not everyone sees it.",
  "profileInfo": "An American comic book writer, editor, publisher, and producer"
}

### update user
PUT http://localhost:9090/users/102
Accept: application/json
Content-Type: application/json

{
  "middleName": "Parker",
  "lastName": "Robertson",
  "username": "Uncle Ben",
  "mobile": "+7 800 5000 500",
  "email": "cliffordpr@gmail.com",
  "profileInfo": "American actor"
}

### retrieve user
GET http://localhost:9090/users/104
Accept: application/json

### retrieve all users
POST http://localhost:9090/users
Accept: application/json

### delete user
DELETE http://localhost:9090/users/104
Accept: application/json

### create post
POST http://localhost:9090/users/104/post
Accept: application/json
Content-Type: application/json

{
  "receiverId": 9890,
  "text": "Guten Morgen liebe Sorgen!"
}

### create message
POST http://localhost:9090/users/104/message
Accept: application/json
Content-Type: application/json

{
  "receiverId": 9890,
  "text": "Guten Morgen liebe Sorgen!"
}

### create friendship relation
POST  http://localhost:9090/users/104/friend
Accept: application/json
Content-Type: application/json

{


}

### create followship relation
POST http://localhost:9090/users/104/follower
Accept: application/json
Content-Type: application/json

{


}