version: '3.5'

services:

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./docker_users_init.sql:/docker-entrypoint-initdb.d/1-docker_users_init.sql"
      - "./docker_databases_init.sql:/docker-entrypoint-initdb.d/2-docker_databases_init.sql"
    ports:
      - "5454:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: db_admin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: db_admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "88:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: